package yipengyu.baway.com.youyuanproject.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import yipengyu.baway.com.youyuanproject.bean.DataBean;
import yipengyu.baway.com.youyuanproject.bean.FriendListDataBean;
import yipengyu.baway.com.youyuanproject.bean.UserInfoDataBean;

import yipengyu.baway.com.youyuanproject.dao.DataBeanDao;
import yipengyu.baway.com.youyuanproject.dao.FriendListDataBeanDao;
import yipengyu.baway.com.youyuanproject.dao.UserInfoDataBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataBeanDaoConfig;
    private final DaoConfig friendListDataBeanDaoConfig;
    private final DaoConfig userInfoDataBeanDaoConfig;

    private final DataBeanDao dataBeanDao;
    private final FriendListDataBeanDao friendListDataBeanDao;
    private final UserInfoDataBeanDao userInfoDataBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataBeanDaoConfig = daoConfigMap.get(DataBeanDao.class).clone();
        dataBeanDaoConfig.initIdentityScope(type);

        friendListDataBeanDaoConfig = daoConfigMap.get(FriendListDataBeanDao.class).clone();
        friendListDataBeanDaoConfig.initIdentityScope(type);

        userInfoDataBeanDaoConfig = daoConfigMap.get(UserInfoDataBeanDao.class).clone();
        userInfoDataBeanDaoConfig.initIdentityScope(type);

        dataBeanDao = new DataBeanDao(dataBeanDaoConfig, this);
        friendListDataBeanDao = new FriendListDataBeanDao(friendListDataBeanDaoConfig, this);
        userInfoDataBeanDao = new UserInfoDataBeanDao(userInfoDataBeanDaoConfig, this);

        registerDao(DataBean.class, dataBeanDao);
        registerDao(FriendListDataBean.class, friendListDataBeanDao);
        registerDao(UserInfoDataBean.class, userInfoDataBeanDao);
    }
    
    public void clear() {
        dataBeanDaoConfig.clearIdentityScope();
        friendListDataBeanDaoConfig.clearIdentityScope();
        userInfoDataBeanDaoConfig.clearIdentityScope();
    }

    public DataBeanDao getDataBeanDao() {
        return dataBeanDao;
    }

    public FriendListDataBeanDao getFriendListDataBeanDao() {
        return friendListDataBeanDao;
    }

    public UserInfoDataBeanDao getUserInfoDataBeanDao() {
        return userInfoDataBeanDao;
    }

}
